# Screen size
SIM_WIDTH = 900
SIM_HEIGHT = 800
UI_WIDTH = 0
HEIGHT = SIM_HEIGHT
WIDTH = SIM_WIDTH + UI_WIDTH

# Global particle values
RADIUS = 2
DRAG = 0.08
MIN_DISTANCE = 0.3
MAX_DISTANCE = 80
MAX_FORCE_DISTANCE = (MIN_DISTANCE + 1) / 2
FORCE_FACTOR = 10
DT = 0.01

# Other
FPS = 60