# Screen size
SIM_WIDTH = 600
SIM_HEIGHT = 600
UI_WIDTH = 200
HEIGHT = SIM_HEIGHT
WIDTH = SIM_WIDTH + UI_WIDTH

# Global particle values
RADIUS = 2
DRAG = 0.05
MIN_DISTANCE = 0.3
MAX_DISTANCE = 80
MAX_FORCE_DISTANCE = (MIN_DISTANCE + 1) / 2
FORCE_FACTOR = 15
DT = 0.01

# Other
FPS = 60